# Generated by Django 4.2.2 on 2023-06-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech', '0002_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
